import type { Sesija } from "./types";

// ─── Helper IDs (stable, deterministic) ──────────────────────────────────────
// All demo data represents realistic, law-abiding workflow snapshots:
//   ses-001 — Mode B, u_radu: pod-001 done, pod-002 has an unstarted 2nd cycle, pod-003 not started
//   ses-002 — Mode A, u_radu: cycle 1 done, cycle 2 active with 1 measurement
//   ses-003 — Mode B, zavrseno: all podsessions done, last cycle has full completionPhases

export const DEMO_SESIJE: Sesija[] = [

  // ─── Sesija 1 — S podsesijama (Mode B), u_radu ───────────────────────────
  // Constraint check:
  //   pod-001: status "zavrseno", cik-001 status "zavrsen" — OK
  //   pod-002: status "u_radu", cik-002 "zavrsen", cik-003 "ceka_pocetno_mjerenje" — OK (active cycle)
  //   pod-003: status "nije_zapoceto" — OK (not started)
  //   session status "u_radu" — CORRECT (active cycles / subsessions still unfinished)
  {
    id: "ses-001",
    isDemo: true,
    naziv_objekta: "Stambena zgrada Ilica 44",
    lokacija: "Zagreb, Ilica 44",
    datum: "2025-04-20",
    serviser: "Tomislav Kovač",
    kontakt_osoba: "Marko Babić (upravitelj)",
    systemCategory: "unknown",
    opis_problema:
      "Smanjena efikasnost grijanja, talog u sustavu, radijatori hladni u zonama B i C.",
    status: "u_radu",
    workMode: "with_subsessions",
    cleaningMode: "descaling",
    podsesije: [
      {
        id: "pod-001",
        naziv: "Kotlovnica – primarni krug",
        redni_broj: 1,
        dio_sustava: "Kotao + primarna pumpa",
        opis_dijela: "Primarni krug centralnog grijanja, čelični kotao.",
        lokacija_unutar_objekta: "Podrumska kotlovnica",
        vrsta_dijela: "Kotlovski krug",
        materijal: "Čelik",
        procijenjeni_volumen: 80,
        pocetni_protok_vrijednost: 20,
        pocetni_protok_jedinica: "l_min",
        pocetni_protok_l_min: 20,
        napomena_protok: "Mjereno na izlaznoj cijevi kotla",
        vrsta_naslage: "Kamenac",
        jacina_problema: "Srednje",
        vizualna_napomena: "Vidljivi talog na stijenkama izmjenjivača",
        servisna_napomena: "Preporučen drugi ciklus ako pH ne poraste u prvih 90 min",
        status: "zavrseno",
        status_reakcije: "dobra",
        kratka_preporuka: "Sustav čist, preporučuje se godišnji preventivni servis.",
        ciklusi: [
          {
            id: "cik-001",
            sessionId: "ses-001",
            subsessionId: "pod-001",
            cycleNumber: 1,
            broj: 1,
            startDateTime: "2025-04-20T08:00:00",
            endDateTime: "2025-04-20T10:30:00",
            timestamp_pocetka: "2025-04-20T08:00:00",
            timestamp_zavrsetka: "2025-04-20T10:30:00",
            reason: "prvi_ciklus",
            previousSolutionDrained: false,
            systemRinsed: false,
            cleanWaterAdded: true,
            waterVolumeL: 80,
            volumen_vode: 80,
            waterTempC: 45,
            waterPh: 7.2,
            chemicalProductName: "AquaDescale Pro",
            kemikalija: "AquaDescale Pro",
            chemicalAmount: 4,
            chemicalUnit: "L",
            chemicalVolumeL: 4,
            kolicina_kemikalije: 4,
            totalSolutionVolumeL: 84,
            chemicalPercent: 4.76,
            waterChemicalRatio: "20.0 : 1",
            baselineFlowLMin: 20,
            initialFlowLMin: 20,
            status: "zavrsen",
            mjerenja: [
              {
                id: "mj-001",
                measuredAt: "2025-04-20T08:30:00",
                timestamp: "2025-04-20T08:30:00",
                ph: 2.8, pH: 2.8,
                temperatureC: 45, temperatura: 45,
                measurementNumber: 1,
                measurementType: "initial_cycle_measurement",
                foamLevel: "jaka",
                colorIndicator: "plava",
                visibleReaction: "jaka",
                flowInputValue: 20, flowInputUnit: "l_min", flowLMin: 20,
                flowChangeFromInitial: 0,
                minutesFromCycleStart: 30,
                note: "Jaka reakcija, mjehurići vidljivi — aktivna kisela zona",
                napomena: "Jaka reakcija, mjehurići vidljivi",
                interpretation: "pH 2.8 — Aktivna kisela zona. Reakcija intenzivna, sredstvo radi.",
              },
              {
                id: "mj-002",
                measuredAt: "2025-04-20T09:30:00",
                timestamp: "2025-04-20T09:30:00",
                ph: 3.6, pH: 3.6,
                temperatureC: 47, temperatura: 47,
                measurementNumber: 2,
                measurementType: "regular",
                previousPh: 2.8,
                phChange: 0.8,
                phRatePerMinute: 0.013,
                foamLevel: "srednja",
                flowInputValue: 23, flowInputUnit: "l_min", flowLMin: 23,
                flowChangeFromInitial: 3,
                flowChangeFromPrevious: 3,
                minutesFromCycleStart: 90,
                minutesFromPreviousMeasurement: 60,
                note: "Reakcija slabi, protok raste",
                napomena: "Reakcija se smanjuje",
                interpretation: "Reakcija slabi. Razmotrite nadopunu sredstva ili novi ciklus.",
              },
              {
                id: "mj-003",
                measuredAt: "2025-04-20T10:15:00",
                timestamp: "2025-04-20T10:15:00",
                ph: 5.2, pH: 5.2,
                temperatureC: 46, temperatura: 46,
                measurementNumber: 3,
                measurementType: "final_cycle",
                previousPh: 3.6,
                phChange: 1.6,
                foamLevel: "nema",
                flowInputValue: 26, flowInputUnit: "l_min", flowLMin: 26,
                flowChangeFromInitial: 6,
                flowChangeFromPrevious: 3,
                minutesFromCycleStart: 135,
                minutesFromPreviousMeasurement: 45,
                note: "Sredstvo iscrpljeno, protok poboljšan za 30%",
                napomena: "Gotovo neutralno, ciklus završen",
                interpretation: "Sredstvo iscrpljeno. Preporučuje se završetak podsesije.",
              },
            ],
            nadopune: [
              {
                id: "nad-001",
                topUpNumber: 1,
                addedAt: "2025-04-20T09:45:00",
                timestamp: "2025-04-20T09:45:00",
                reason: "ph_brzo_raste" as const,
                chemicalProductName: "AquaDescale Pro",
                kemikalija: "AquaDescale Pro",
                amount: 1.5,
                unit: "L" as const,
                addedChemicalVolumeL: 1.5,
                kolicina: 1.5,
                previousTotalSolutionVolumeL: 84,
                newTotalSolutionVolumeL: 85.5,
                previousChemicalVolumeL: 4,
                totalChemicalVolumeL: 5.5,
                newChemicalPercent: 6.43,
                previousPh: 3.6,
                requiresFollowUpMeasurement: true as const,
                note: "pH porastao brže od očekivanog, dodana nadopuna",
                napomena: "pH porastao prebrzo, dodana nadopuna",
                createdAt: "2025-04-20T09:45:00",
                updatedAt: "2025-04-20T09:45:00",
              },
            ],
          },
        ],
      },
      {
        id: "pod-002",
        naziv: "Radijatori – zona B (2. i 3. kat)",
        redni_broj: 2,
        dio_sustava: "Sekundarni krug zona B",
        opis_dijela: "Aluminijski radijatori na 2. i 3. katu, 12 kom.",
        lokacija_unutar_objekta: "2. i 3. kat, hodnici i stanovi",
        vrsta_dijela: "Cjevovod",
        materijal: "Čelik",
        procijenjeni_volumen: 55,
        pocetni_protok_vrijednost: 15,
        pocetni_protok_jedinica: "l_min",
        napomena_protok: "Izmjereno balans ventilom zone B",
        vrsta_naslage: "Miješane naslage",
        jacina_problema: "Jako",
        vizualna_napomena: "Tamni mulj u ispusnom ventilu",
        status: "u_radu",
        status_reakcije: "slaba",
        kratka_preporuka: "Preporučuje se drugi ciklus s pojačanom dozom.",
        ciklusi: [
          {
            id: "cik-002",
            sessionId: "ses-001",
            subsessionId: "pod-002",
            cycleNumber: 1,
            broj: 1,
            startDateTime: "2025-04-20T11:00:00",
            endDateTime: "2025-04-20T13:00:00",
            timestamp_pocetka: "2025-04-20T11:00:00",
            timestamp_zavrsetka: "2025-04-20T13:00:00",
            reason: "prvi_ciklus",
            previousSolutionDrained: false,
            systemRinsed: false,
            cleanWaterAdded: true,
            waterVolumeL: 55,
            volumen_vode: 55,
            waterTempC: 42,
            waterPh: 7.4,
            chemicalProductName: "AlumTech Cleaner",
            kemikalija: "AlumTech Cleaner",
            chemicalAmount: 2.5,
            chemicalUnit: "L",
            chemicalVolumeL: 2.5,
            kolicina_kemikalije: 2.5,
            totalSolutionVolumeL: 57.5,
            chemicalPercent: 4.35,
            waterChemicalRatio: "22.0 : 1",
            baselineFlowLMin: 15,
            initialFlowLMin: 15,
            status: "zavrsen",
            mjerenja: [
              {
                id: "mj-004",
                measuredAt: "2025-04-20T11:30:00",
                timestamp: "2025-04-20T11:30:00",
                ph: 3.5, pH: 3.5,
                temperatureC: 42, temperatura: 42,
                measurementNumber: 1,
                measurementType: "initial_cycle_measurement",
                foamLevel: "srednja",
                colorIndicator: "plavo_zelena",
                visibleReaction: "normalna",
                flowInputValue: 15, flowInputUnit: "l_min", flowLMin: 15,
                flowChangeFromInitial: 0,
                minutesFromCycleStart: 30,
                note: "Umjerena reakcija, pH u radnoj zoni",
                napomena: "Umjerena reakcija",
                interpretation: "pH 3.5 — Aktivna kisela zona. Reakcija normalna.",
              },
              {
                id: "mj-005",
                measuredAt: "2025-04-20T12:30:00",
                timestamp: "2025-04-20T12:30:00",
                ph: 5.0, pH: 5.0,
                temperatureC: 43, temperatura: 43,
                measurementNumber: 2,
                measurementType: "final_cycle",
                previousPh: 3.5,
                phChange: 1.5,
                phRatePerMinute: 0.025,
                foamLevel: "nema",
                flowInputValue: 17, flowInputUnit: "l_min", flowLMin: 17,
                flowChangeFromInitial: 2,
                flowChangeFromPrevious: 2,
                minutesFromCycleStart: 90,
                minutesFromPreviousMeasurement: 60,
                note: "Reakcija završena, slaba učinkovitost — drugi ciklus preporučen",
                napomena: "Reakcija gotovo završena",
                interpretation: "Sredstvo iscrpljeno. Slaba poboljšanje protoka — preporučuje se novi ciklus s jačom dozom.",
              },
            ],
            nadopune: [],
          },
          {
            // Cycle 2 is started but waiting for initial measurement.
            // This is a valid real-world state: operator filled chemical, not yet measured.
            id: "cik-003",
            sessionId: "ses-001",
            subsessionId: "pod-002",
            cycleNumber: 2,
            broj: 2,
            startDateTime: "2025-04-20T13:30:00",
            timestamp_pocetka: "2025-04-20T13:30:00",
            reason: "otopina_iscrpljena",
            previousSolutionDrained: true,
            systemRinsed: true,
            cleanWaterAdded: true,
            waterVolumeL: 55,
            volumen_vode: 55,
            waterTempC: 44,
            waterPh: 7.3,
            chemicalProductName: "AlumTech Cleaner",
            kemikalija: "AlumTech Cleaner",
            chemicalAmount: 3.5,
            chemicalUnit: "L",
            chemicalVolumeL: 3.5,
            kolicina_kemikalije: 3.5,
            totalSolutionVolumeL: 58.5,
            chemicalPercent: 5.98,
            waterChemicalRatio: "15.7 : 1",
            baselineFlowLMin: 17,
            initialFlowLMin: 17,
            status: "ceka_pocetno_mjerenje",
            mjerenja: [],
            nadopune: [],
          },
        ],
      },
      {
        id: "pod-003",
        naziv: "Radijatori – zona C (4. kat)",
        redni_broj: 3,
        dio_sustava: "Sekundarni krug zona C",
        opis_dijela: "Aluminijski radijatori na 4. katu.",
        lokacija_unutar_objekta: "4. kat",
        vrsta_dijela: "Cjevovod",
        materijal: "Čelik",
        procijenjeni_volumen: 30,
        vrsta_naslage: "Nepoznato",
        jacina_problema: "Blago",
        status: "nije_zapoceto",
        status_reakcije: "nepoznato",
        ciklusi: [],
      },
    ],
  },

  // ─── Sesija 2 — Bez podsesija (Mode A), u_radu ───────────────────────────
  // Constraint check:
  //   cik-010: status "zavrsen" — OK
  //   cik-011: status "aktivan", 1 measurement — OK (active cycle in progress)
  //   session status "u_radu" — CORRECT
  {
    id: "ses-002",
    isDemo: true,
    naziv_objekta: "Obiteljska kuća Jankovićeva 12",
    lokacija: "Zagreb, Jankovićeva 12",
    datum: "2025-04-22",
    serviser: "Ante Marić",
    kontakt_osoba: "Vesna Janković",
    systemCategory: "unknown",
    opis_problema:
      "Kompletni sustav grijanja – jednozonski, čelik. Preventivno godišnje čišćenje.",
    status: "u_radu",
    workMode: "no_subsessions",
    cleaningMode: "descaling",
    podsesije: [],
    ciklusi: [
      {
        id: "cik-010",
        sessionId: "ses-002",
        cycleNumber: 1,
        broj: 1,
        startDateTime: "2025-04-22T09:00:00",
        endDateTime: "2025-04-22T11:30:00",
        timestamp_pocetka: "2025-04-22T09:00:00",
        timestamp_zavrsetka: "2025-04-22T11:30:00",
        reason: "prvi_ciklus",
        previousSolutionDrained: false,
        systemRinsed: false,
        cleanWaterAdded: true,
        waterVolumeL: 60,
        volumen_vode: 60,
        waterTempC: 43,
        waterPh: 7.1,
        chemicalProductName: "AquaDescale Pro",
        kemikalija: "AquaDescale Pro",
        chemicalAmount: 3,
        chemicalUnit: "L",
        chemicalVolumeL: 3,
        kolicina_kemikalije: 3,
        totalSolutionVolumeL: 63,
        chemicalPercent: 4.76,
        waterChemicalRatio: "20.0 : 1",
        baselineFlowLMin: 18,
        initialFlowLMin: 18,
        status: "zavrsen",
        mjerenja: [
          {
            id: "mj-010",
            measuredAt: "2025-04-22T09:30:00",
            timestamp: "2025-04-22T09:30:00",
            ph: 2.9, pH: 2.9,
            temperatureC: 43, temperatura: 43,
            measurementNumber: 1,
            measurementType: "initial_cycle_measurement",
            foamLevel: "vrlo_jaka",
            colorIndicator: "plava",
            visibleReaction: "jaka",
            flowInputValue: 18, flowInputUnit: "l_min", flowLMin: 18,
            flowChangeFromInitial: 0,
            minutesFromCycleStart: 30,
            note: "Intenzivna reakcija, mnogo taloga — aktivna kisela zona",
            napomena: "Intenzivna reakcija, mnogo taloga",
            interpretation: "pH 2.9 — Aktivna kisela zona. Reakcija je intenzivna.",
          },
          {
            id: "mj-011",
            measuredAt: "2025-04-22T10:30:00",
            timestamp: "2025-04-22T10:30:00",
            ph: 4.5, pH: 4.5,
            temperatureC: 44, temperatura: 44,
            measurementNumber: 2,
            measurementType: "regular",
            previousPh: 2.9,
            phChange: 1.6,
            phRatePerMinute: 0.027,
            foamLevel: "slaba",
            flowInputValue: 22, flowInputUnit: "l_min", flowLMin: 22,
            flowChangeFromInitial: 4,
            flowChangeFromPrevious: 4,
            minutesFromCycleStart: 90,
            minutesFromPreviousMeasurement: 60,
            note: "Reakcija slabi, protok poboljšan",
            napomena: "Reakcija se stabilizira",
            interpretation: "Sredstvo slabi. pH 4.5 — razmotriti završetak ili novi ciklus.",
          },
          {
            id: "mj-012",
            measuredAt: "2025-04-22T11:15:00",
            timestamp: "2025-04-22T11:15:00",
            ph: 6.0, pH: 6.0,
            temperatureC: 43, temperatura: 43,
            measurementNumber: 3,
            measurementType: "final_cycle",
            previousPh: 4.5,
            phChange: 1.5,
            foamLevel: "nema",
            flowInputValue: 25, flowInputUnit: "l_min", flowLMin: 25,
            flowChangeFromInitial: 7,
            flowChangeFromPrevious: 3,
            minutesFromCycleStart: 135,
            minutesFromPreviousMeasurement: 45,
            note: "Sredstvo iscrpljeno, protok poboljšan za ~39%",
            napomena: "Neutralno, ciklus završen",
            interpretation: "Sredstvo iscrpljeno. Protok poboljšan. Preporučuje se drugi ciklus.",
          },
        ],
        nadopune: [],
      },
      {
        // Active cycle — in progress, 1 measurement recorded, waiting for next.
        id: "cik-011",
        sessionId: "ses-002",
        cycleNumber: 2,
        broj: 2,
        startDateTime: "2025-04-22T12:00:00",
        timestamp_pocetka: "2025-04-22T12:00:00",
        reason: "otopina_iscrpljena",
        previousSolutionDrained: true,
        systemRinsed: true,
        cleanWaterAdded: true,
        waterVolumeL: 60,
        volumen_vode: 60,
        waterTempC: 42,
        waterPh: 7.2,
        chemicalProductName: "AquaDescale Pro",
        kemikalija: "AquaDescale Pro",
        chemicalAmount: 2.5,
        chemicalUnit: "L",
        chemicalVolumeL: 2.5,
        kolicina_kemikalije: 2.5,
        totalSolutionVolumeL: 62.5,
        chemicalPercent: 4.0,
        waterChemicalRatio: "24.0 : 1",
        baselineFlowLMin: 25,
        initialFlowLMin: 25,
        status: "aktivan",
        hasInitialMeasurement: true,
        mjerenja: [
          {
            id: "mj-013",
            measuredAt: "2025-04-22T12:30:00",
            timestamp: "2025-04-22T12:30:00",
            ph: 3.2, pH: 3.2,
            temperatureC: 42, temperatura: 42,
            measurementNumber: 1,
            measurementType: "initial_cycle_measurement",
            foamLevel: "srednja",
            colorIndicator: "zelena",
            visibleReaction: "normalna",
            flowInputValue: 25, flowInputUnit: "l_min", flowLMin: 25,
            flowChangeFromInitial: 0,
            minutesFromCycleStart: 30,
            note: "Drugi ciklus — aktivna kisela zona, blaža reakcija nego prvi",
            napomena: "Drugi ciklus, blaža reakcija nego prvi",
            interpretation: "pH 3.2 — Aktivna kisela zona. Reakcija normalna za drugi ciklus.",
          },
        ],
        nadopune: [
          {
            id: "nad-010",
            topUpNumber: 1,
            addedAt: "2025-04-22T12:50:00",
            timestamp: "2025-04-22T12:50:00",
            reason: "ph_previsok" as const,
            chemicalProductName: "AquaDescale Pro",
            kemikalija: "AquaDescale Pro",
            amount: 0.5,
            unit: "L" as const,
            addedChemicalVolumeL: 0.5,
            kolicina: 0.5,
            previousTotalSolutionVolumeL: 62.5,
            newTotalSolutionVolumeL: 63.0,
            previousChemicalVolumeL: 2.5,
            totalChemicalVolumeL: 3.0,
            newChemicalPercent: 4.76,
            previousPh: 3.2,
            requiresFollowUpMeasurement: true as const,
            note: "Preventivna nadopuna — pH stabiliziran",
            napomena: "pH porastao brže od očekivanog",
                createdAt: "2025-04-22T12:50:00",
                updatedAt: "2025-04-22T12:50:00",
              },
            ],
          },
        ],
      },

  // ─── Sesija 3 — Završena, s podsesijama (Mode B) ─────────────────────────
  // Constraint check:
  //   pod-004: status "zavrseno", cik-004 "zavrsen" with completionPhases — OK
  //   session status "zavrseno" — CORRECT (all subsessions done, completionPhases present)
  {
    id: "ses-003",
    isDemo: true,
    naziv_objekta: "Poslovna zgrada Radnička 80",
    lokacija: "Zagreb, Radnička 80",
    datum: "2025-04-18",
    serviser: "Ante Marić",
    kontakt_osoba: "Igor Matić (facility manager)",
    systemCategory: "unknown",
    opis_problema: "Godišnje preventivno čišćenje sustava grijanja i hlađenja.",
    status: "zavrseno",
    workMode: "with_subsessions",
    cleaningMode: "descaling",
    podsesije: [
      {
        id: "pod-004",
        naziv: "Fan coil sustav – sjeverno krilo",
        redni_broj: 1,
        dio_sustava: "Rashladni krug – sjever",
        opis_dijela: "Bakreni pločasti izmjenjivači fan coil jedinica.",
        lokacija_unutar_objekta: "Sjeverno krilo, svi katovi",
        vrsta_dijela: "Pločasti izmjenjivač",
        materijal: "Bakar",
        materijal_upozorenje: "Oprez: provjeriti kompatibilnost sredstva s bakrom.",
        procijenjeni_volumen: 120,
        pocetni_protok_vrijednost: 25,
        pocetni_protok_jedinica: "l_min",
        vrsta_naslage: "Kamenac",
        jacina_problema: "Srednje",
        status: "zavrseno",
        status_reakcije: "dobra",
        kratka_preporuka: "Sustav u odličnom stanju, sljedeći servis za 12 mj.",
        ciklusi: [
          {
            id: "cik-004",
            sessionId: "ses-003",
            subsessionId: "pod-004",
            cycleNumber: 1,
            broj: 1,
            startDateTime: "2025-04-18T07:30:00",
            endDateTime: "2025-04-18T11:00:00",
            timestamp_pocetka: "2025-04-18T07:30:00",
            timestamp_zavrsetka: "2025-04-18T11:00:00",
            reason: "prvi_ciklus",
            previousSolutionDrained: false,
            systemRinsed: false,
            cleanWaterAdded: true,
            waterVolumeL: 120,
            volumen_vode: 120,
            waterTempC: 38,
            waterPh: 7.0,
            chemicalProductName: "CopperSafe Descaler",
            kemikalija: "CopperSafe Descaler",
            chemicalAmount: 6,
            chemicalUnit: "L",
            chemicalVolumeL: 6,
            kolicina_kemikalije: 6,
            totalSolutionVolumeL: 126,
            chemicalPercent: 4.76,
            waterChemicalRatio: "20.0 : 1",
            baselineFlowLMin: 25,
            initialFlowLMin: 25,
            status: "zavrsen",
            mjerenja: [
              {
                id: "mj-007",
                measuredAt: "2025-04-18T08:00:00",
                timestamp: "2025-04-18T08:00:00",
                ph: 2.7, pH: 2.7,
                temperatureC: 38, temperatura: 38,
                measurementNumber: 1,
                measurementType: "initial_cycle_measurement",
                foamLevel: "jaka",
                colorIndicator: "plava",
                visibleReaction: "jaka",
                flowInputValue: 25, flowInputUnit: "l_min", flowLMin: 25,
                flowChangeFromInitial: 0,
                minutesFromCycleStart: 30,
                note: "Intenzivna reakcija — aktivna kisela zona",
                napomena: "Intenzivna reakcija",
                interpretation: "pH 2.7 — Aktivna kisela zona. Reakcija jaka, kamenac se otapa.",
              },
              {
                id: "mj-008",
                measuredAt: "2025-04-18T10:00:00",
                timestamp: "2025-04-18T10:00:00",
                ph: 5.8, pH: 5.8,
                temperatureC: 39, temperatura: 39,
                measurementNumber: 2,
                measurementType: "final_cycle",
                previousPh: 2.7,
                phChange: 3.1,
                phRatePerMinute: 0.026,
                foamLevel: "nema",
                flowInputValue: 34, flowInputUnit: "l_min", flowLMin: 34,
                flowChangeFromInitial: 9,
                flowChangeFromPrevious: 9,
                minutesFromCycleStart: 150,
                minutesFromPreviousMeasurement: 120,
                note: "Završeno — protok poboljšan za 36%, sustav čist",
                napomena: "Završeno, sustav čist",
                interpretation: "Sredstvo iscrpljeno. Protok značajno poboljšan. Ciklus uspješno završen.",
              },
            ],
            nadopune: [],
            // ─── Completion phases — required for status "zavrseno" ──────────
            // All three phases completed: ispiranje → neutralizacija → zavrsniPH
            completionPhases: {
              ispiranje: {
                id: "isp-004",
                completedAt: "2025-04-18T11:15:00",
                solutionDrained: true,
                drainDurationMinutes: 8,
                systemRinsedWithCleanWater: true,
                rinsePhInlet: 7.1,
                rinsePhOutlet: 7.3,
                rinsePhValue: 7.3,
                rinsePhDiff: 0.2,
                rinsePhStatus: "prihvatljivo",
                neutralizationRequired: false,
                rinseWaterAppearance: "bistra",
                rinseSediment: "nema",
                note: "Ispiranje prihvatljivo — neutralizacija nije potrebna (ΔpH = 0.2).",
              },
              neutralizacija: undefined,
              zavrsniPH: {
                id: "zph-004",
                completedAt: "2025-04-18T11:45:00",
                inletPhValue: 7.1,
                ph1: 7.1,
                ph2: 7.2,
                minutesBetweenMeasurements: 10,
                finalFlowLMin: 34,
                finalWaterAppearance: "bistra",
                status: "prihvatljiv",
                technicianConfirmed: true,
                note: "Završni pH u rasponu mrežne vode. Sustav siguran za puštanje u pogon.",
              },
              procjenaKamenca: undefined, // ← Algoritam će izračunati pri završetku sesije
              // (estimateScaleByReactionParams koristi identičnu logiku kao produkcija)
              technicianReadyConfirmed: true,
            },
          },
        ],
      },
    ],
  },
];
